# Generated by Django 5.0.1 on 2024-02-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=155)),
                ('sector', models.CharField(max_length=200)),
            ],
        ),
    ]
